/**
 * Configuration constants
 */

module.exports = {
  // Resource limits
  MAX_CPU_TIME_LIMIT: 5.0,
  MAX_CPU_EXTRA_TIME: 2.0,
  MAX_WALL_TIME_LIMIT: 10.0,
  MAX_MEMORY_LIMIT: 128000, // KB
  MAX_STACK_LIMIT: 64000, // KB
  MAX_MAX_PROCESSES_AND_OR_THREADS: 60,
  MAX_MAX_FILE_SIZE: 1024, // KB

  // Default limits
  CPU_TIME_LIMIT: 2.0,
  CPU_EXTRA_TIME: 0.5,
  WALL_TIME_LIMIT: 5.0,
  MEMORY_LIMIT: 128000,
  STACK_LIMIT: 64000,
  MAX_PROCESSES_AND_OR_THREADS: 60,
  MAX_FILE_SIZE: 1024,

  // Other settings
  NUMBER_OF_RUNS: 1,
  ENABLE_COMPILER_OPTIONS: true,
  ENABLE_COMMAND_LINE_ARGUMENTS: true,
  REDIRECT_STDERR_TO_STDOUT: false,
  ENABLE_NETWORK: false,
};
